CatalogCrud.Web/Controllers/CatalogController.cs
using AutoMapper;
using CatalogCrud.BLL.DTO;
using CatalogCrud.BLL.Exceptions;
using CatalogCrud.BLL.Interfaces;
using CatalogCrud.Web.Models.ViewModels;
using CatalogCrud.Web.Util;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CatalogCrud.Web.Controllers
{
    //[Authorize(Roles = "admin, catalog_admin, app_admin")]
    public class CatalogController : Controller
    {
        private ICatalogService CatalogService;
        private IFieldService FieldService;
        private IValueService ValueService;

        public CatalogController(ICatalogService catalogService, IFieldService fieldService, IValueService valueService)
        {
            CatalogService = catalogService;
            FieldService = fieldService;
            ValueService = valueService;
        }

        [AllowAnonymous]
        public ActionResult Index(int ? page)
        {
            var ItemsPerPage = 10;
            var catalogs = CatalogService.GetAll().ToList();
            var catalogVMList = Mapper.Map<IEnumerable<CatalogVM>>(catalogs);

            return View(catalogVMList.ToPagedList(page ?? 1, ItemsPerPage));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CatalogVM model)
        {
            if (ModelState.IsValid)
            {
                var catalogDTO = Mapper.Map<CatalogDTO>(model);
                CatalogService.Add(catalogDTO);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(Guid? id)
        {
            try
            {
                var catalogDTO = CatalogService.Get(id);
                var catalogVM = Mapper.Map<CatalogVM>(catalogDTO);

                return View(catalogVM);
            }
            catch (ArgumentNullException)
            {
                return RedirectToRoute(new { controller = "Message", action = "Error", message = Messages.IdIsNull });
            }
            catch (NotFoundException)
            {
                return RedirectToRoute(new { controller = "Message", Action = "Error", message = Messages.NotFound });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CatalogVM model)
        {
            if (ModelState.IsValid)
            {
                var catalogDTO = Mapper.Map<CatalogDTO>(model);
                CatalogService.Update(catalogDTO);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Delete(Guid? id)
        {
            var result = CatalogService.Delete(id);

            if (result.Succeeded)
                return RedirectToAction("Index");
            else
                return RedirectToRoute(new { controller = "Message", action = "Error", message = result.Message });
        }

        public ActionResult AttachedFields(Guid? catalogId)
        {
            try
            {
                var catalog = CatalogService.Get(catalogId);
                var catalogVM = Mapper.Map<CatalogVM>(catalog);

                return View(catalogVM);
            }
            catch (ArgumentNullException)
            {
                return RedirectToRoute(new { controller = "Message", action = "Error", message = Messages.IdIsNull });
            }
            catch (NotFoundException)
            {
                return RedirectToRoute(new { controller = "Message", action = "Error", message = Messages.NotFound });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AttachField(Guid catalogId, Guid fieldId)
        {
            var fieldVM = Mapper.Map<FieldVM>(FieldService.Get(fieldId));
            var result = CatalogService.AttachField(catalogId, fieldId);

            if (result.Succeeded)
                return PartialView(fieldVM);
            else
                return RedirectToRoute(new { controller = "Message", action = "PartialError", message = result.Message });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public string DetachField(Guid catalogId, Guid fieldId)
        {
            var result = CatalogService.DetachField(catalogId, fieldId);

            if (result.Succeeded)
                return "success";
            else
                return "fail";
        }

        public ActionResult Values(Guid? catalogId, int? page)
        {
            try
            {
                int ItemsPerPage = 10;
                ViewBag.CatalogId = catalogId;
                ViewBag.Fields = Mapper.Map<IEnumerable<FieldVM>>(CatalogService.GetOrderedCatalogFieldList(catalogId).ToList()).ToList();

                var valuesByRows = ValueService.GetCatalogValuesByRows(catalogId);
                var rows = Funcs.ConvertDTOValuesByRowsToVMValuesByRows(valuesByRows);

                return View(rows.ToPagedList(page ?? 1, ItemsPerPage));
            }
            catch (ArgumentNullException)
            {
                return RedirectToRoute(new { controller = "Message", action = "Error", message = Messages.IdIsNull });
            }
        }

        public ActionResult UploadFile(Guid catalogId)
        {
            ViewBag.CatalogId = catalogId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(Guid catalogId)
        {
            var file = Request.Files["file"];
            if (file.ContentLength > 0)
            {
                string validFileType = ".csv";
                string fileExt = Path.GetExtension(file.FileName).ToLower();

                if (fileExt == validFileType)
                {
                    CatalogService.RemoveCatalogValues(catalogId);
                    var csvlines = Funcs.GetFileContentByLines(file);
                    var catalogFields = CatalogService.GetOrderedCatalogFieldList(catalogId);
                    var csvFields = csvlines[0].Split('|').Select(f => Funcs.ClearStringAndToLower(f)).ToList();
                    for (int line = 1; line < csvlines.Length; line++)
                    {
                        if (!string.IsNullOrEmpty(csvlines[line]))
                        {
                            var values = csvlines[line].Split('|');
                            for (int value = 0; value < values.Length; value++)
                            {
                                var valueField = catalogFields.Where(cf => cf.Name.ToLower() == csvFields[value]).FirstOrDefault();
                                if (valueField != null)
                                {
                                    var valueDTO = new ValueDTO
                                    {
                                        Title = values[value], // need to encode in utf8
                                        Row = line,
                                        FieldId = valueField.Id,
                                        CatalogId = catalogId
                                    };
                                    ValueService.Add(valueDTO);
                                }
                            }
                        }
                    }

                    return RedirectToAction("Index");
                }
                else
                    TempData["fail"] = "Файл должен быть формата '.csv.'";
            }
            else
                TempData["fail"] = "Выберите файл.";

            ViewBag.CatalogId = catalogId;
            return View("UploadFile");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRow(Guid catalogId, int rowNumber)
        {
            ViewBag.RowNumber = rowNumber;
            var fields = CatalogService.GetOrderedCatalogFieldList(catalogId).ToList();
            var fieldVMList = Mapper.Map<IEnumerable<FieldVM>>(fields).ToList();

            return PartialView(fieldVMList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddedRow(IEnumerable<ValueVM> values)
        {
            ValueDTO valueDTO;
            foreach (var value in values)
            {
                valueDTO = Mapper.Map<ValueDTO>(value);
                ValueService.Add(valueDTO);
            }

            int row = values.First().Row;
            Guid catalogId = values.First().CatalogId;
            ViewBag.CatalogId = catalogId;
            ViewBag.RowNumber = row;
            ViewBag.Values = ValueService.GetCatalogValuesByRow(catalogId, row);

            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRow(Guid catalogId, int rowNumber)
        {
            try
            {
                ViewBag.RowNumber = rowNumber;
                ViewBag.Row = ValueService.GetCatalogValuesByRow(catalogId, rowNumber);

                return PartialView();
            }
            catch (Exception ex)
            {
                return RedirectToRoute(new { controller = "Message", action = "PartialError", mesasge = ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditedRow(IEnumerable<ValueVM> values)
        {
            ValueDTO valueDTO;
            foreach (var value in values)
            {
                valueDTO = Mapper.Map<ValueDTO>(value);
                ValueService.Update(valueDTO);
            }

            int row = values.First().Row;
            Guid catalogId = values.First().CatalogId;
            ViewBag.CatalogId = catalogId;
            ViewBag.RowNumber = row;
            ViewBag.Values = ValueService.GetCatalogValuesByRow(catalogId, row);

            return PartialView();
        }

CatalogCrud.Web/Controllers/FieldController.cs
using AutoMapper;
using CatalogCrud.BLL.DTO;
using CatalogCrud.BLL.Exceptions;
using CatalogCrud.BLL.Interfaces;
using CatalogCrud.Web.Models.ViewModels;
using CatalogCrud.Web.Util;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CatalogCrud.Web.Controllers
{
    //[Authorize(Roles = "admin, catalog_admin, app_admin")]
    public class FieldController : Controller
    {
        private IFieldService FieldService;

        public FieldController(IFieldService fieldService)
        {
            FieldService = fieldService;
        }

        [AllowAnonymous]
        public ActionResult Index(int? page)
        {
            var ItemsPerPage = 10;
            var fields = FieldService.GetAll().ToList();
            var fieldVMList = Mapper.Map<IEnumerable<FieldVM>>(fields);

            return View(fieldVMList.ToPagedList(page ?? 1, ItemsPerPage));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FieldVM model)
        {
            if (ModelState.IsValid)
            {
                var fieldDTO = Mapper.Map<FieldDTO>(model);
                FieldService.Add(fieldDTO);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(Guid? id)
        {
            try
            {
                var fieldDTO = FieldService.Get(id);
                var fieldVM = Mapper.Map<FieldVM>(fieldDTO);

                return View(fieldVM);
            }
            catch (ArgumentNullException)
            {
                return RedirectToRoute(new { controller = "Message", action = "Error", message = Messages.IdIsNull });
            }
            catch (NotFoundException)
            {
                return RedirectToRoute(new { controller = "Message", action = "Error", message = Messages.NotFound });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FieldVM model)
        {
            if (ModelState.IsValid)
            {
                var fieldDTO = Mapper.Map<FieldDTO>(model);
                FieldService.Update(fieldDTO);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Delete(Guid? id)
        {
            var result = FieldService.Delete(id);

            if (result.Succeeded)
                return RedirectToAction("Index");
            else
                return RedirectToRoute(new { controller = "Message", action = "Error", message = result.Message });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FindFields(string value)
        {
            var foundFields = FieldService.FindFields(value).ToList();
            var foundFieldVMList = Mapper.Map<IEnumerable<FieldVM>>(foundFields);

            return PartialView(foundFieldVMList.ToList());
        }
    }
}

CatalogCrud.Web/Views/Shared/Loading.cshtml
<div class="modal hide" tabindex="-1" role="dialog" id="loadingDialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ожидайте</h5>
            </div>
            <div class="modal-body">
                Выполняется обработка запроса.
            </div>
        </div>
    </div>
</div>

CatalogCrud.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/PagedList.css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #007bff;">
        <div class="container">
            @Html.ActionLink("Справочники", "Index", "Catalog", null, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Поля", "Index", "Field", null, new { @class = "nav-link" })
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Вход", "Login", "Account", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Регистрация", "Register", "Account", null, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="account" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @User.Identity.Name
                            </a>
                            <div class="dropdown-menu" aria-labelledby="account">
                                @Html.ActionLink("Сменить Email", "ChangeEmail", "Account", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Сменить пароль", "ChangePassword", "Account", null, new { @class = "dropdown-item" })
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Выйти", "Logout", "Account", null, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (TempData["success"] != null)
        {
            <div id="message-div" class="p-3 mb-2 bg-success text-white">
                <div class="container">
                    <b>@TempData["success"]</b>
                    <span class="float-right message-div-close" onclick="closeMessageDiv()"><i class="fa fa-times" aria-hidden="true"></i></span>
                </div>
            </div>
        }
        @if (TempData["fail"] != null)
        {
            <div id="message-div" class="p-3 mb-2 bg-danger text-white">
                <div class="container">
                    <b>@TempData["fail"]</b>
                    <span class="float-right message-div-close" onclick="closeMessageDiv()"><i class="fa fa-times" aria-hidden="true"></i></span>
                </div>
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Справочники</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/app.js")
    @RenderSection("scripts", required: false)
</body>
</html>